import os
import sys
import SCons.cpp
import rtconfig

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
Export('RTT_ROOT')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

sconstruct = File('SConstruct')
fn = sconstruct.rfile()
name = fn.name
building_dir = os.path.dirname(fn.abspath)

env = Environment(tools = ['mingw'],
        AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
        CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
        CXX = rtconfig.CXX, AR = rtconfig.AR, ARFLAGS = '-rc',
        LINK = rtconfig.LINK,
        CPPPATH = [os.path.join(building_dir, '..', 'platform'), 
                RTT_ROOT + '/include',
                RTT_ROOT + '/components/finsh',
                RTT_ROOT + '/components/dfs', 
                RTT_ROOT + '/components/dfs/include',
                RTT_ROOT + '/components/libc/newlib',
                ])
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
Export('env')

PrepareModuleBuilding(env, RTT_ROOT)

objs = SConscript('arduino/SConscript')
TARGET = 'arduino'

# build program 
env.Library(TARGET, objs)
